### ISSUE TITLE
Using react-figma for sync Figma & production

### ISSUE THREAD

**Issue by ilyalesik** [simareeno/figma-and-production#2]
Hi, @simareeno! What do you think maybe [react-figma](https://github.com/react-figma/react-figma) can simplify plugin creation? It allows to describe design system like React app:

```typescript
import * as React from "react"

import * as someIcon from './icons/icon.png';

export const App = () => {
    return (
        <Page name="Design system">
            <Frame name="Icons">
                 <Component name="SomeIcon">
                     <Rectangle
                        style={{
                           backgroundImage: someIcon
                        }}
                     />
                 </Component>
           </Frame>
        </Page>
    );
};
```

Checkout [design system example](https://github.com/react-figma/react-figma/tree/master/examples/design-system). Thanks!

**Comment by simareeno** [comment]
Hi, @ilyalesik.

Saw your tool and I like how declarative it is. But I have two reasons not to use it:
1. I will have 2 APIs. Yours and Figma's. And they are different.
2. May be I get it wrong, but I won't be able to do things like this:
```ts
const svg: FrameNode = figma.createNodeFromSvg(item.content);
for (const child of svg.children) {
    icon.appendChild(child);
}
svg.remove();
```
You suggest to use png, but I want svg. So I could copy it.

**Comment by ilyalesik** [comment]
Thanks for the valuable feedback! `createNodeFromSvg` really does not support now. I will add an issue about that.
